### ISSUE TITLE
Preparation 1: Funny Stories

### ISSUE THREAD

**Issue by dykesb** [STA518-01-W21/community#1]
Tell a funny story of a teacher or professor.

I'll start things off! In grad school when I was taking a course on [nonparametric statistics](https://en.wikipedia.org/wiki/Nonparametric_statistics) theory my professor open up the required textbook to reference page numbers. After giving pages a quick read, he would say, "I don't know why the authors would do it this way..."

He was the author...

**Comment by Stevenbentley7** [comment]
In middle school, each of the classrooms had a _Smartboard_ placed in them. Within the first week, three of my teachers had ruined the expensive new technology with a sharpie. The staff did not think it was as funny as us students.

<img width="371" alt="Screenshot 2021-01-18 132204" src="https://user-images.githubusercontent.com/77634960/104951288-3b4d0c80-5990-11eb-86ee-8f3964b73a4e.png">

**Comment by Jockusct** [comment]
My Ethics Professor had a very well developed vocabulary and most of the time it was difficult to interpret what he was saying. The class he taught was discussion based and at times, us students would use  "Generation Z" terms in the discussion. These included terms such as [high key](https://stayhipp.com/glossary/what-does-high-key-mean/) and [low key](https://www.mentalfloss.com/article/71558/lowkey-word-thats-lowkey-snuck-our-vocabulary).

As many words as this Professor had in his vocabulary, these terms confused him and we would spend more than half of our class time trying to explain to him what they meant instead of learning about ethics.


![Screen Shot 2021-01-18 at 4 46 04 PM](https://user-images.githubusercontent.com/73850780/104965425-af95a900-59ac-11eb-8f63-7ae25ca47b40.png)

**Comment by mikaelaberg** [comment]
While in undergraduate I worked in the biology lab prep here gv, and the greenhouse is apart of the biology department.  I would sometimes help out in the greenhouse with watering and other tasks as needed. Two summers ago we had to move all plants from our arid room (all desert and arid plants) so that the window cleaner crew could get to certain spots. While moving the plants my coworker and I went to move a large cactus. The balance was off and I caught part of the cactus with my bare arm. Thankfully no spines broke off, so I rinsed my arm and continued the day. 24 hours later I go to my boss and it appears that I might have had a reaction to the cactus. She sent me to the urgent care with another coworker and the doctor there was ***very*** confused as to where I had gotten poked by a cactus. I was no longer allowed to help with any of the arid plants. Here is a picture of said cactus. 
![58318608191__DD68C04E-2801-4482-BA44-F123382675FB](https://user-images.githubusercontent.com/61589685/104957217-b7008680-599b-11eb-8cde-c27b94affa84.JPG)

Our [greenhouse](https://www.instagram.com/barbarakindschigreenhousegvsu/) is a wonderful place and sometimes they will open the greenhouse to the public. It is small but during finals, it's really nice to walk around and unwind!

**Comment by IsaacHRai96** [comment]
During my undergraduate degree at [Calvin College](https://calvin.edu/) I had an awfully quiet professor for one of my _microelectronics_ classes. He had to use a microphone during class in order for the class to be able to hear him. During our very first quiz he stepped out of the room to use the bathroom and forgot to take his mic off. I don't need to elaborate on the noises we heard as we were all working on our quizzes. I don't believe anyone ever mentioned it to him, so I'm not sure if he knows it even happened.

**Comment by JenksNat** [comment]
During my time at [Muskegon Community College](https://www.muskegoncc.edu) we had a scheduled active shooter drill in each class that day and one of my professors was fed up with doing the drill already multiple times throughout the day so he continued to lecture about **World War II** as there was a blaring siren stating that there was an active shooter.

**Comment by CarleyDziewicki** [comment]
I once had a professor that would constantly use the *same phrase* and we as students started to keep track during class. We would take these tallies and add them all up, at the end of the semester the final number was **staggering**, I don't recall what it was anymore.

**Comment by liam-hart** [comment]
My friends and I used to play a game called **Counter Strike: Global Offensive** where in-game gun skins sold for real money. Common skins would usually go for around a dollar but rare skins could fetch up to at least $2000 with some selling for ridiculous prices like $30,000. My friend had a YouTube channel at the time where he uploaded a video of him betting his **$300** item on a 50/50 coinflip, which he lost and had a hilarious reaction to. Someone sent the video to my teacher and he played the entire video in class, for everyone to see, while my friend was also in the class, curse words and all. The class was dying of laughter and it was a legendary moment for my friend group. I would link it but I'm not sure if it would be appropriate haha, so here is a picture of the pixels worth $300 that he bet away:
![image](https://user-images.githubusercontent.com/77597977/104980863-92290500-59d5-11eb-9973-a38b1dcb3f83.png)

**Comment by Barthur006** [comment]
During my undergraduate studies, we had these one Senior Professor who taught us **Measure Theory.** I remember one early morning ,I went to his office for a meeting and upon arrival , he was making a call so i had to wait for a couple of minutes and after the call, he started searching around for something. After some seconds He just said '_where is my phone_', whiles he was holding it . it was so funny then.

**Comment by dswhite5** [comment]
In undergrad I had to take a music theory course as part of the core curriculum. We had a research paper due that I had procrastinated on. Class was at **8 am** and I stayed awake the entire night to write the paper. When I showed up to class I explained to the professor that I had not slept and would like to skip class that day to sleep. He responded with  "*I can't actually tell you that you can skip class, but you gotta do what you gotta do*" I turned in my paper, walked out of class and promptly went to bed.

**Comment by steensme** [comment]
I was a biology major at [Calvin College](www.calvin.edu), but as part of a liberal arts education, I took a class on Greek Mythology. On a particular day, we were learning about _Leda and the Swan_, where the god Zeus takes on the form of a swan and seduces Leda. The professor explained the story and how, because of this, Leda became pregnant. He then paused a moment and said, "We'll let the biologists explain exactly how that happened."

**Comment by weglarzd** [comment]
During my undergrad, I took a course in [Actuarial Probability](https://en.wikipedia.org/wiki/Actuary). The professor came in each day and made up quotes similar to Confucius. One day he made the quote *"Confucius say learn probability or the odds will be against you."* This was probably one of his better ones he came up with.

**Comment by austinpfiffner** [comment]
During my undergrad we once convinced the professor to have class at the **bar**. So the next day we had class at the _only local pub in town_.

**Comment by lewhart** [comment]
I once had a professor at my local community college who stopped the _entire class session_ and lead us outside because she spotted a cute dog who happened to be named **Fred**.  It was indeed a pretty cute dog I must admit

**Comment by tscheidel** [comment]
My freshman year **American Civilization** class was two semesters long. At the start of the winter semester my professor came in and said we were going to spend some time watching a movie that had cultural significance to the time period we were studying that semester (everything post civil war). We spent the rest of the week's class periods watching *The Godfather*. He also set up a movie night for our class where we watched *National Treasure*. It was great.

**Comment by ScholtenC** [comment]
I got plenty but I'll name one good one.

Went to the Joint Mathematics Meetings Conference to present our REU research in San Diego years ago. I did my REU program in the summer with Valparaiso in Combinatorics. My college roommate at the time came with me since he spent the summer doing Lie Algebra Research at GV and also got an invitation to present. Having a Valparaiso and GV entourage led to quite a few adventures that week. Including meeting and befuddling then Fields Medal winner Cedric Villani, *Other Fun Story*. One of the afterparties included me, my roommate, a couple other GV grad students and about a half dozen GV Math Professors each of us putting money down on a dealer's choice poker game in the lobby of one of the fancy downtown Hotels. *What we were doing maybe wasn't exactly following California State law at the time...* 

Me being unimaginative and each of us a few drinks in, one of my sad choices when I dealt was just a vanilla Texas Hold'em allowing roundabout straights. I won that hand on a roundabout straight and got a few glares from the profs for thinking I might have done sleight of hand on the shuffling. *I did not*. After a couple hours into poker we were getting comfortable and then all the sudden a full unit SWAT team on mission, full tactical gear, stormed by our table to go up the Lobby stairs to what I assumed breach one of the hotel rooms on an upper level. One of the men in the rear of the formation stopped at our table, howled out **"FREEZE"** and pointed his M4 right at me in particular. We all dropped our cards, chips and drinks and put our hands up and for a hot couple of second we all had the same thought we were all about to get arrested. He then said "Just kidding" and caught up with his unit. We never saw them again.

**Comment by danielciaravino** [comment]
On one of the last days of a particular French class I took as a part of my undergraduate studies at Aquinas college, our professor looked at all of us and said "Ok I have 2 options for today - _game or video_". The whole class looked perplexed at one another but timidly answered video not knowing what we were getting ourselves into. We then spent the rest of the class period coming up with a plot and film, all in French, for one of our last days together.  The plot of the video was that my character was mysteriously found dead and there was a full investigation into the cause.

Unbeknownst to me, the professor [posted the video on the department page ](https://www.aquinas.edu/world-languages/french/student-productions)and it is still there today.

![image](https://user-images.githubusercontent.com/59859632/105196155-568f5780-5b09-11eb-8fb7-04cd8d4045b3.png)

**Comment by waltonty** [comment]
I guess I've had some boring professors compared to the rest of you, but I had a Business Essentials class where my professor had to take a leave of absence. It was a pretty small school where there wasn't a great organization structure, and the guy who took over teaching the course was **NOT** prepared. He basically scratched the whole syllabus and spent most of the class sessions talking about experiences he'd had and how to game the system, etc. Which was helpful to a certain extent. He had some good stories and I wasn't particularly invested in the class to begin with, but yeah that happened.



![image](https://user-images.githubusercontent.com/77644451/105206956-f1d9fa00-5b14-11eb-8826-fd40ad3728f8.png)

**Comment by aaronstrat** [comment]
One time my professor handed out a test but it was actually for a different class that he taught. It was only until **everyone failed** that the professor and class realized it was the wrong test.  We had to retake the proper test the following class session and the class did much better.

![image](https://user-images.githubusercontent.com/77688519/105220415-ae3bbc00-5b25-11eb-9742-74d170a1f93c.png)

**Comment by knoppj** [comment]
# The Singing Student
When I was in high school, one of my teachers called in sick and we found out earlier in the day that the substitute teacher was someone we **REALLY** didn't care for.  One of the kids in my class hid in a closet in the classroom that looked something like [this](https://www.bing.com/images/search?view=detailV2&ccid=89HHCxm1&id=41AEF800FE9DA3B8F4127368291193D0FBC909CB&thid=OIP.89HHCxm1HNyLx83gItOsPgHaHa&mediaurl=https%3a%2f%2fwww.childrensfactory.com%2fwp-content%2fuploads%2fsites%2f1%2f1519.jpg&exph=2000&expw=2000&q=classroom+closets&simid=608055060545933021&ck=B4EDE39770851F47A01B0B5E3B33171C&selectedIndex=4&FORM=IRPRST&ajaxhist=0).  When the substitute teacher was taking attendance, and called his name, he jumped out and started singing the national anthem.
Two things resulted from this:
* The class started laughing
*  He was kicked out 

I'm sure he got in trouble for the stunt, but having had this much time to reflect on it, I think he probably won in the end for not having to sit through the remainder of that boring class.  Thankfully, our teacher returned the very next day.

**Comment by tweedya** [comment]
I had a business ethics class as part of my undergrad course work. The professor was a long time veteran of giant companies like GE, IBM, etc. His son had written a book about his road to recovery from being an addict. He touted the book heavily and the fact that his son had been on several national news shows. A few years later it came out that the son had made the whole thing up. Maybe this falls more under the ironic category than funny?

**Comment by treed8887** [comment]
During one chemistry class on nuclear chemistry, a professor turned off the lights in the room, put on some hazmat clothing and told the class he had a radioactive rock in a box he was holding. He then proceeded to carefully remove the **glow-in-the-dark** rock with iron tongs and "accidentally" dropped it next to some of the students in the front row. They must have jumped 5 feet out of their chairs, LOL!

[Professor Pranks](https://www.youtube.com/results?search_query=professor+pranks+students+)

**Comment by rydeckik** [comment]
I had a professor who liked to include pics of cute little animals in his lecture slides. One of these pics showed a dog high in the air because he was so startled by a little mouse. One student said, "it doesn't look real." The professor whirled around and yelled, "**Who said it wasn't real?**" :laughing:
