### ISSUE TITLE
Creating a pull request for activity

### ISSUE THREAD

**Issue by liam-hart** [STA518-01-W21/community#7]
I am trying to push my code into github from R Studio but it is not showing up on github. I tried playing around with it but now I am in the main branch and it won't let me switch back to my user branch. I completed my code, knit, committed the changes, and hit the push button. When I go onto github and try to create a pull request, though, nothing shows up in my user branch. Not sure what to do from here
![Screenshot (4)](https://user-images.githubusercontent.com/77597977/106171742-ecf1f780-615f-11eb-9aa1-debadfdc188e.png)
![Screenshot (5)](https://user-images.githubusercontent.com/77597977/106171750-f0857e80-615f-11eb-912c-3eb687bed9e4.png)

**Comment by dykesb** [comment]
A couple of items:

- It looks like you typed the `git config ...` code in your **Console** instead of your **Terminal** (next tab over in the lower-left-hand area)
- It looks like you are still in the `main` branch, not your `username` branch (in the **Git** pane, it says `main` next to the purple branch icon) so you might have made these changes to the `main` branch. To switch to your `username` branch, click on `main` in the **Git** pane and select your branch.

We might need to talk about this more during a live session (e.g., drop-in hours or schedule an appointment) so we can see if anything else needs to be looked into.
